version: '3'
# usage:
# sudo docker-compose build
# sudo docker-compose up
services:
  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    expose:
      - '27017'

  beacon-cli:
    environment:
      MONGODB_HOST: mongodb
    image: northwestwitch/cgbeacon2
    container_name: beacon-cli
    links:
      - mongodb
    command: bash -c 'cgbeacon2 add demo'

  beacon-web:
    environment:
      MONGODB_HOST: mongodb
    image: northwestwitch/cgbeacon2
    container_name: beacon-web
    links:
      - mongodb
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: bash -c 'cgbeacon2 run --host 0.0.0.0'
