site_name: cgbeacon2 docs

nav:
    - Home: index.md
    - Running the app in Docker: docker_run.md
    - Installation on a virtual environment: env-install.md
    - Loading datasets and variants: loading.md
    - Removing datasets and variants: removing.md
    - Queries: queries.md

theme: readthedocs
